import React,{useRef,useState} from 'react';
import {Users,Plus,Check,Download,Upload,ArrowRight,FolderHeart} from 'lucide-react';
import {addProfile,renameProfile,selectProfile,createBackup,parseBackup,restoreBackup,MAX_BACKUP_BYTES,MAX_PROFILES,type Profile,type Workspace,type Backup} from './storage';
import {courseLessons} from './content';
import type {LearningGrade} from './grades';
export default function Family({profiles,currentId,onUpdate}:{profiles:Profile[];currentId:string;onUpdate:(w:Workspace)=>void}){
 const [name,setName]=useState('');const [grade,setGrade]=useState<LearningGrade>('1');const [message,setMessage]=useState('');const [error,setError]=useState('');const [working,setWorking]=useState(false);const [preview,setPreview]=useState<Backup|null>(null);const [fileName,setFileName]=useState('');const [renameId,setRenameId]=useState<string|null>(null);const [nickname,setNickname]=useState('');const fileRef=useRef<HTMLInputElement>(null);
 function run(action:()=>Workspace,success:string){setError('');setMessage('');try{onUpdate(action());setMessage(success);return true}catch(e:any){setError(e.message);return false}}
 function add(e:React.FormEvent){e.preventDefault();if(run(()=>addProfile(name,grade),'New learner added and selected.'))setName('')}
 function download(){setError('');setMessage('');try{const backup=createBackup();const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`literacy-quest-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('Backup download requested. Keep the JSON file in a safe place; it contains learner nicknames and writing.')}catch(e:any){setError(e.message)}}
 async function inspect(file:File|undefined){setPreview(null);setMessage('');setError('');setFileName('');if(!file)return;setWorking(true);try{if(file.size>MAX_BACKUP_BYTES)throw Error('Choose a Literacy Quest backup no larger than 16 MB.');const b=parseBackup(await file.text());setPreview(b);setFileName(file.name)}catch(e:any){setError(e.message)}finally{setWorking(false);if(fileRef.current)fileRef.current.value=''}}
 function restore(){if(!preview)return;const count=preview.profiles.length;if(run(()=>restoreBackup(preview),`${count} restored ${count===1?'profile was':'profiles were'} added. Select a restored learner below to continue. Your original profiles are unchanged.`)){setPreview(null);setFileName('')}}
 return <><div className="page-heading"><div><p className="eyebrow">A space for every explorer</p><h1>Learners & backups</h1><p>Keep each learner’s discoveries in their own place.</p></div><span className="family-count"><Users size={18}/>{profiles.length} / {MAX_PROFILES} learners</span></div>
 {error&&<p className="family-message family-error" role="alert">{error}</p>}{message&&<p className="family-message" role="status">{message}</p>}
 <div className="learner-grid">{profiles.map(p=><article className={`learner-card ${p.id===currentId?'is-current':''}`} key={p.id}><div className="learner-card-heading"><span className="learner-avatar" aria-hidden="true">{Array.from(p.name)[0]?.toUpperCase()}</span><div><h2>{p.name}</h2><p>Grade {p.grade} guide</p></div>{p.id===currentId&&<span className="learner-current"><Check size={14}/>Current</span>}</div><div className="learner-stats"><span><strong>{courseLessons(p.grade).filter(l=>p.records[l.id]?.completed).length}</strong> / 16 in this course</span><span><strong>{Object.values(p.records).filter(r=>r.draft.trim()).length}</strong> pieces · all courses</span></div><div className="learner-actions"><button className="secondary" disabled={p.id===currentId} onClick={()=>run(()=>selectProfile(p.id),`${p.name} is now selected.`)}>{p.id===currentId?'Selected':'Switch learner'}{p.id!==currentId&&<ArrowRight size={16}/>}</button><button className="text-button" onClick={()=>{setRenameId(p.id);setNickname(p.name);setError('')}} aria-label={`Rename ${p.name}`}>Rename</button></div>{renameId===p.id&&<form className="rename-form" onSubmit={e=>{e.preventDefault();if(run(()=>renameProfile(p.id,nickname),'Nickname updated.'))setRenameId(null)}}><label htmlFor={`rename-${p.id}`}>New nickname</label><input id={`rename-${p.id}`} value={nickname} maxLength={32} onChange={e=>setNickname(e.target.value)} required/><div><button className="primary" type="submit">Save name</button><button className="text-button" type="button" onClick={()=>setRenameId(null)}>Cancel</button></div></form>}</article>)}</div>
 <section className="family-add panel"><div><span className="icon-box green"><Plus size={22}/></span><h2>Add a learner</h2><p>A nickname is enough. Each learner gets separate progress, writing, and a grade guide.</p></div><form onSubmit={add}><div><label htmlFor="learner-name">Nickname</label><input id="learner-name" value={name} onChange={e=>setName(e.target.value)} maxLength={32} placeholder="e.g. River" required autoComplete="off"/></div><div><label htmlFor="learner-grade">Starting guide</label><select id="learner-grade" value={grade} onChange={e=>setGrade(e.target.value as LearningGrade)}><option value="K">Kindergarten · Listen, play & tell</option><option value="1">Grade 1 · Read with support</option><option value="2">Grade 2 · Explain & extend</option><option value="3">Grade 3 · Read, prove & compose</option><option value="4">Grade 4 · Infer, compare & explain</option><option value="5">Grade 5 · Connect, reason & author</option></select></div><button className="primary" type="submit" disabled={!name.trim()||profiles.length>=MAX_PROFILES}><Plus size={17}/>Add learner</button></form></section>
 <div className="backup-grid"><section className="panel backup-panel"><span className="icon-box green"><Download size={23}/></span><h2>Keep a copy of their discoveries</h2><p>Download all learners’ saved progress, answers, writing, and grade guides in one backup file.</p><button className="primary" onClick={download}><Download size={17}/>Download backup</button><small>Keep this JSON file outside your GitHub repository. It contains personal learning records.</small></section><section className="panel backup-panel"><span className="icon-box blue"><Upload size={23}/></span><h2>Bring discoveries back</h2><p>Choose a backup from this app. Review it first, then restore it as new learner profiles.</p><label className="backup-file-label" htmlFor="backup-file">Literacy Quest backup (.json, up to 16 MB)</label><input id="backup-file" ref={fileRef} type="file" accept=".json,application/json" disabled={working} onChange={e=>inspect(e.target.files?.[0])}/><small>Existing profiles stay unchanged. You can use the same file on another device.</small>{working&&<p role="status">Checking backup…</p>}</section></div>
 {preview&&<section className="restore-preview panel" aria-label="Backup preview"><p className="eyebrow">Review before restoring</p><h2>{preview.profiles.length} {preview.profiles.length===1?'learner':'learners'} in this backup</h2><p className="backup-filename">{fileName} · Saved {new Date(preview.exportedAt).toLocaleDateString()}</p><ul>{preview.profiles.map((p,i)=><li key={i}><strong>{p.name}</strong><span>Grade {p.grade} · {Object.values(p.records).filter(r=>r.completed).length} complete across courses · {Object.values(p.records).filter(r=>r.draft.trim()).length} writing pieces</span></li>)}</ul><p>Copies will be added with “(restored)” in their names. This does not replace or merge existing work.</p><div className="actions"><button className="primary" onClick={restore}><FolderHeart size={18}/>Restore as new learners</button><button className="text-button" onClick={()=>{setPreview(null);setFileName('')}}>Cancel restore</button></div></section>}
 <p className="family-storage-note">Profiles are stored in this browser, without accounts or passwords. They are separate workspaces, not private logins. Clearing site data removes them; a downloaded backup lets you restore saved work. Automatic device sync is not included.</p></>;
}
