import React from 'react';
import {ArrowRight,BookOpen,Check,Compass,Leaf} from 'lucide-react';
import {grades,strands,standardsUrl,type LearningGrade} from './grades';
export default function GradePicker({preview,onPreview,current,onChoose}:{preview:string;onPreview:(g:string)=>void;current:LearningGrade;onChoose:(g:LearningGrade)=>void}){
 const grade=grades.find(g=>g.id===preview)!;
 return <><div className="page-heading"><div><p className="eyebrow">Room to grow, K–5</p><h1>Find your next chapter.</h1><p>Explore the goals. Choose the support that helps you grow.</p></div><span className="grade-map-badge"><Leaf size={18}/> Every reader has a pace.</span></div>
 <div className="grade-grid" role="group" aria-label="Explore grade goals">{grades.map(g=><button className={`grade-card ${g.available?'available':''}`} key={g.id} aria-pressed={preview===g.id} onClick={()=>onPreview(g.id)} aria-label={`${g.label}: ${g.available?(g.id==='K'?'16 Kindergarten lessons available':(g.id==='3'||g.id==='4'||g.id==='5')?`16 Grade ${g.id} lessons available`:'16 shared lessons available'):'Coming soon'}`}><span className="grade-card-top"><span className="grade-number">{g.id}</span>{current===g.id&&<span className="current-grade"><Check size={13}/> My guide</span>}</span><strong>{g.label}</strong><span>{g.name}</span><small className={g.available?'ready-badge':'soon-badge'}>{g.available?(g.id==='K'?'16 K lessons':(g.id==='3'||g.id==='4'||g.id==='5')?`16 Grade ${g.id} lessons`:'16 shared lessons'):'Coming soon'}</small></button>)}</div>
 <section className="grade-detail" aria-label={`${grade.label} learning goals`}><div className="grade-detail-intro"><div><p className="eyebrow">{grade.label.toUpperCase()} · {grade.available?'Available now':'Curriculum preview'}</p><h2>{grade.name}</h2><p>{grade.tag}</p></div><Compass size={44} strokeWidth={1.3}/></div>
 <div className="goal-grid">{grade.goals.map((goal,i)=><article key={strands[i]}><small>{strands[i]}</small><h3>{goal}</h3></article>)}</div>
 <div className="grade-next"><div><strong>{grade.available?'A four-week adventure, with your kind of support.':'Lessons are coming. Curiosity can start today.'}</strong><p>{grade.available?(grade.id==='K'?'Sixteen Kindergarten lessons with listening games, letter exploration, short read-alouds, and spoken ideas. Plan for 10–15 minutes with a grown-up.':grade.id==='3'?'Sixteen original Grade 3 lessons with longer readings, evidence choices, and paragraph writing. Explore nature, characters, community plans, and useful ideas. Plan for about 20–30 minutes.':grade.id==='4'?'Sixteen original Grade 4 lessons with four-paragraph readings, inference, evidence comparison, paired sources, and two-paragraph information writing. Plan for about 25–35 minutes or split a lesson into two sessions.':grade.id==='5'?'Sixteen original Grade 5 lessons with two or three sources per lesson, source notes, accurate quotation, and three-paragraph reports. Plan for about 30–40 minutes or split reading and writing into separate sessions.':`Grades 1 and 2 share the same 16 readings, questions, and saved work. ${grade.id==='1'?'Grade 1 adds read-together guidance and sentence starters.':'Grade 2 adds explanation prompts and optional writing extensions.'}`):'This is a preview of planned goals. There are no lessons or completion scores for this grade yet.'}</p></div>{grade.available?<button className="primary" onClick={()=>onChoose(grade.id as LearningGrade)}>Use {grade.label} guide<ArrowRight size={18}/></button>:<button className="secondary" onClick={()=>onPreview(current)}>View available lessons<ArrowRight size={18}/></button>}</div>
 <div className="grade-family"><BookOpen size={22}/><p><strong>{grade.available?'Try this approach':'Try this offline'}</strong>{grade.idea}</p></div></section>
 <details className="standards-note"><summary>For grown-ups: how these goals were planned</summary><p>Selected goals reference Common Core ELA strands. They are a planning guide, not a complete grade curriculum or a reading-level test. Local expectations may differ. Choose support based on your child’s needs.</p><p>Reference points for {grade.label}: {grade.refs.join(' · ')}.</p><p>The 16-lesson course offers focused practice. These broad goals are not all covered or assessed by it. Kindergarten explores selected letters and sounds; it is not a complete alphabet or phonics course. Grade 2 extensions are optional and reviewed by a grown-up.</p><a href={standardsUrl} target="_blank" rel="noopener noreferrer">Read the Common Core ELA standards (PDF, new tab)</a></details></>;
}
